### ISSUE TITLE
Name in pyproject.toml is different to other names

### ISSUE THREAD

**Issue by alastair** [hapytex/django-single-session#6]
pyproject.toml calls this "django-single-login":

https://github.com/hapytex/django-single-session/blob/d10a172cb65977075248c13c88b7ed48ba10446b/pyproject.toml#L2

which causes some problems when trying to install the package using pip directly from github. It'd be nice to standardise this with the repository name

**Comment by KommuSoft** [comment]
fixed, thanks.
